### ISSUE TITLE
Allow users to be add/view multiple public channels

### ISSUE THREAD

**Issue by patricknowlan** [18F/slackin#4]
I requested an invite to the cap-public channel then requested an invite for the devops-public channel. I expected to be granted access to both channels. When I log in, I am only able to view the cap-public channel (the first channel I requested) and neither the devops-public nor the midas-public channel. When I request access on the slackin page the form notifies me that I am already part of the team when requesting a new invite for the channels I do not have access to.

I would like to be a part of all of the public channels!  Thanks!

**Comment by afeld** [comment]
Unfortunately this is [a restriction of Slack](https://slack.zendesk.com/hc/en-us/articles/202518103-Restricted-Account-and-Single-Channel-Guest-FAQ)...the only way to give public access to multiple channels is via a Restricted Account, which would be an additional cost (a deal-breaker for us). Sorry!

Made an issue to make this more obvious: https://github.com/rauchg/slackin/issues/72

**Comment by patricknowlan** [comment]
Might be interesting to think about a public slack domain for 18f or even one for the entire government? There would be no limit on the number of channels a user would have access to.

**Comment by afeld** [comment]
If only it were that simple :smirk: We had a lot of conversations about it and looked at various Slack/non-Slack options, but this ended up making the most sense (and being fastest) for procurement, negotiated terms of service, record retention, etc. reasons, despite this main drawback. Let us know if you would like your single channel to be switched.

/cc https://github.com/18F/ideas/issues/5
