### ISSUE TITLE
Heroku deployment doesn't set variable properly? 

### ISSUE THREAD

**Issue by mlissner** [18F/slackin#5]
Don't know anything about Heroku, but when I use the deploy button for this app, and configure it with a channel, the resulting deployment doesn't seem to have a channel defined. 

For example, the dyno I created is here:

```
https://flp-talk.herokuapp.com/
```

And if you try to use it while watching the network panel, you'll see that the post it does uses the parameters:

```
{"channel":null,"email":"mike@yadayadayada.org"}
```

If I look in the config variables for the Heroku app, I can see that SLACK_CHANNEL is set properly, so I have no idea where the problem is. Seems like it should be an easy thing though for somebody that knows Heroku.

**Comment by mlissner** [comment]
Also, note that the app does seem to know about the channel, as you can see in the screenshot:

![screenshot from 2015-07-08 14 42 05](https://cloud.githubusercontent.com/assets/236970/8583073/a082ac40-257f-11e5-94d4-c50e27c4793c.png)

**Comment by afeld** [comment]
Seems like it may be https://github.com/rauchg/slackin/issues/63? Anyway, my guess is it's a configuration issue, either for slackin or the Slack organization.
