### ISSUE TITLE
Can't access single channel

### ISSUE THREAD

**Issue by jackiekazil** [18F/slackin#7]
(I know this isn't the right place for this, but this is the closest repo that I thought might be a place to throw this ticket.)

@NoahKunin, et al
I am trying to sign into 18F slack single channel -- my 2FA on slack is sent to my personal phone. Is there a way to over right? Right now, I can't login.

**Comment by afeld** [comment]
@jackiekazil Just disabled 2FA on your account, so hopefully it should prompt you to set it up next time you try to sign in, and you should be good to go. Feel free to re-open if that doesn't work!

**Comment by jackiekazil** [comment]
Thank you! That worked!

On Wed, Jan 13, 2016 at 4:16 PM, Aidan Feldman notifications@github.com
wrote:

> @jackiekazil https://github.com/jackiekazil Just disabled 2FA on your
> account, so hopefully it should prompt you to set it up next time you try
> to sign in, and you should be good to go. Feel free to re-open if that
> doesn't work!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/slackin/issues/7#issuecomment-171435122.

## 

Jacqueline Kazil | @jackiekazil
